### ISSUE TITLE
This fails to install according to the instructions on Mac OSX 

### ISSUE THREAD

**Issue by princeriley** [wcandillon/jsoniq#67]
/usr/local/lib/node_modules/jsoniq/dist/lib/cli/Main.js:11
    .action(file => {
                  ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/jsoniq/bin/jsoniq:8:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

**Comment by princeriley** [comment]
command prompt> npm install jsoniq -save

command prompt > jsoniq compile query.jq

/usr/local/lib/node_modules/jsoniq/dist/lib/cli/Main.js:11
    .action(file => {
                  ^

**Comment by bburns** [comment]
Not sure where things went wrong - these steps worked for me on Mac -

```
mkdir jsoniq-test
cd jsoniq-test
npm install jsoniq -g
npm init -y
npm install jsoniq -save
jsoniq compile query.jq
node query.js
```
